### ISSUE TITLE
Introducing a Game Interface and Dynamic Configuration Management?

### ISSUE THREAD

**Issue by hyperioxx** [CHollingworth/Lamp#41]
With each game possessing its own class and hardcoded configurations, the extensibility and dynamic manageability of the mod manager across various games and mods present scalability challenges.

This PR proposes the introduction of a Game Interface and dynamic configuration management, enabling the mod manager to seamlessly support various games and mods with ease and consistency.

1. Implementing a Game Interface
A strategy pattern is employed to define a common interface for all game-specific classes, ensuring a standardized set of operations across all games.

```cpp
class IGame {
public:
    virtual ~IGame() = default;
    virtual void install_mod(const Mod& mod) = 0;
    virtual void uninstall_mod(const Mod& mod) = 0;
    // ... additional methods ...
};
```
Each game will have a dedicated class implementing this interface, thus ensuring consistency and ease of extension.

2. Dynamic Configuration Management
To dynamically manage various games and mods, configurations can be sourced from a local file or a remote server, offering centralized management and real-time updates.

a. From a Configuration File:
Utilizing a JSON, XML, or YAML file to store game and mod configurations, and parsing it at runtime.

Example JSON Configuration:

```json
{
    "skyrim": {
        "mod_source": "https://example.com/skyrim-mods",
        "install_path": "/path/to/skyrim/mods",
        "dependencies": ["Dependency1", "Dependency2"]
    },
    // ... additional games ...
}
```

b. From a Remote Server:
Fetching configurations from a remote server, enabling centralized management and real-time updates without manual user intervention.

Example API Endpoint:
```
GET https://api.example.com/games/configurations
```

**Comment by hyperioxx** [comment]
Just an idea

**Comment by CHollingworth** [comment]
On point 1. this is already being implemented into 1.0.8 alongside major core reworks in lamp, 2 is a long term goal of mine to have master-lists for dependencies, types, requirements however this is unfeasible right now due to time constraints and the shear volume of work that would entail, however using the api integrations for nexus this should be feasible for nexus mods links once that is operational. I'd also, if your interested in the development of lamp, recommend joining our development discord as i post core updates there more frequently.

**Comment by alterNERDtive** [comment]
Would implementing the Nexus API mean that Lamp could pull updates automatically? <3

**Comment by CHollingworth** [comment]
That it would.
